# https://github.com/MikeRogers0/MikeRogersIO/blob/master/bridgetown.config.yml

collections:
  posts:
    permalink: /blog/:slug.*
  cooking:
    permalink: /cooking/:slug.*
  sprints:
    permalink: /sprints/:slug.*
    output: true
  tils:
    permalink: /today-i-learned/:slug.*
    output: true
