# https://github.com/MikeRogers0/MikeRogersIO/blob/master/bridgetown.config.yml

collections:
  posts:
    permalink: /blog/:slug.*
    title: "Blog posts"
  cooking:
    permalink: /cooking/:slug.*
  sprints:
    permalink: /sprints/:slug.*
    output: true
    future: true
  tils:
    permalink: /today-i-learned/:slug.*
    output: true
    sort_by: order
    sort_direction: descending
    title: "Today I Learned"
  tangible_works:
    permalink: /tangible-work/:slug.*
    output: true
    sort_by: order
    sort_direction: descending
    title: "Tangible Work"
feed:
  collections:
    - tils
    - tangible_works
